NumPy is the fundamental library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.

# Creating Arrays

In [1]:
# Now let's import numpy
import numpy as np

# np.zeros

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# Lets create 2D arrays
# In NumPy, each dimension is called an axis.
#The number of axes is called the rank.
#For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
#The first axis has length 3, the second has length 4.
#An array's list of axis lengths is called the shape of the array.
#For example, the above matrix's shape is (3, 4).
#The rank is equal to the shape's length.
#The size of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a.shape

(3, 4)

In [14]:
a.ndim #equal to len(a.shape)

2

In [15]:
a.size

12

# N-dimensional arrays

In [18]:
# Numpy arrays have the type ndarray s:
type(np.zeros((3,4)))

numpy.ndarray

# np.ones


In [19]:
# many other numpy functions create ndarrays
# Here's 3x4 matrix full of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# np.full

In [21]:
# Creates an array of the given shape initialized with the given value.
# here's a 3x4 matrix full of 𝜋
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

# np.empty

In [22]:
# An uninitialized 2x3 array(its content is not predictablr, as it is whatever
# is in memory at that point):
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# np.array

In [25]:
# Of course you can initialize an ndarray using a regular python array.
# Just call the array function:
np.array([[1,2,3,4], [10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

# np.arange

In [56]:
np.arange(1,5,0.5)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6])

In [29]:
# However, whrn dealing with floats, the exact number of elements in the array
# is not always predictable. For example, consider this:

print(np.arange(0, 5/3, 1/3))
print(np.arange(0, 5/3, 0.3333333333))
print(np.arange(0, 5/3, 0.3333333334))


[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333]


# np.linspace

In [30]:
# For this reason, it is generally preferable to use the linspace
#function instead of arange when working with floats.
#The linspace function returns an array containing a specific number
#of points evenly distributed between two values
#(note that the maximum value is included, contrary to arange):

print(np.linspace(0, 5/3, 6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


# np.rand and np.randn

In [31]:
# A number of functions are available in NumPy's random module
# to create ndarrays initialized with random values.
#For example, here is a 3x4 matrix initialized with random
#floats between 0 and 1 (uniform distribution):

np.random.rand(3,4)

array([[0.77900997, 0.67450712, 0.74837582, 0.84560515],
       [0.0920073 , 0.77225307, 0.63929556, 0.57002346],
       [0.91890226, 0.59438181, 0.38374731, 0.69094477]])

Here's a 3x4 matrix containing random floats sampled from a univariate normal distribution (Gaussian distribution) of mean 0 and variance 1:

In [32]:
np.random.randn(3,4)

array([[ 2.50016901,  0.62749591,  0.15039531, -1.54986132],
       [-0.90473878,  0.05809634, -0.4844587 , -1.46932625],
       [ 1.03395686,  1.34133504,  1.03385373, -0.92619669]])

# np.fromfunction

In [33]:
def my_function(z,y,x):
    return x + 10 * y + 100 * z
np.fromfunction(my_function, (3,2,10))

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]],

       [[100., 101., 102., 103., 104., 105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]],

       [[200., 201., 202., 203., 204., 205., 206., 207., 208., 209.],
        [210., 211., 212., 213., 214., 215., 216., 217., 218., 219.]]])

NumPy first creates three ndarrays (one per dimension), each of shape (3, 2, 10). Each array has values equal to the coordinate along a specific axis. For example, all elements in the z array are equal to their z-coordinate:

[[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]]
  
  
So the terms x, y and z in the expression x + 10 * y + 100 * z above are in fact ndarrays (we will discuss arithmetic operations on arrays below). The point is that the function my_function is only called once, instead of once per element. This makes initialization very efficient.

# Array data
# dtype

NumPy's ndarrays are also efficient in part because all their elements must have the same type (usually numbers). You can check what the data type is by looking at the dtype attribute:

In [34]:
c = np.arange(1,5)
print(c.dtype,c)

int64 [1 2 3 4]


In [35]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

float64 [1. 2. 3. 4.]


Instead of letting NumPy guess what data type to use, you can set it explicitly when creating an array by setting the dtype parameter:

In [36]:
d = np.arange(1,5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


# itemsize

In [39]:
# The itemsize attribute returns the size (in bytes) of each item:
e = np.arange(1, 5, dtype=np.complex64)
e.itemsize

8

# data buffer

In [40]:
# An array's data is actually stored in memory as a flat (one dimensional) byte buffer.
# It is available via the data attribute (you will rarely need it, though).

f = np.array([[1,2], [1000, 2000]], dtype=np.int32)
f.data

In python 2, f.data is a buffer. In python, it is a memoryview.

In [41]:
if (hasattr(f.data, "tobytes")):
    data_bytes = f.data.tobytes() # python 3
else :
    data_bytes = memoryview(f.data).tobytes() # pyhton 2
    
data_bytes
    

b'\x01\x00\x00\x00\x02\x00\x00\x00\xe8\x03\x00\x00\xd0\x07\x00\x00'

# Reshaping an array

In [42]:
# In place
# Changing the shape of an array is as simple as setting its shape attributes.
# However, the array's size must remain the same.

g = np.arange(24)
print(g)
print("rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
rank: 1


In [45]:
g.shape=(6,4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


In [46]:
g.shape = (2,3,4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


# reshape

The reshape function returns a new ndarray object pointing at the same data. This means that modifying one array will also modify the other.


In [52]:
g2 = g.reshape(4,6)
print(g2)
print("Rank:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank: 2


In [53]:
g2[1,2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [54]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

# ravel

Finally, the ravel function returns a new one-dimensional ndarray that also points to the same data

In [55]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Arithmetic operations

All the usual arithmetic operators (+, -, *, /, //, **, etc.) can be used with ndarrays. They apply elementwise:

In [58]:
a = np.array([14, 23, 32, 41])
b =np.array([5, 4, 3, 2])

print("a + b=", a + b)
print("a-b=", a - b)
print("a * b=", a * b)
print ("a / b=", a / b)
print("a // b=", a//b)
print("a % b=", a % b)
print("a ** b=", a ** b)

a + b= [19 27 35 43]
a-b= [ 9 19 29 39]
a * b= [70 92 96 82]
a / b= [ 2.8         5.75       10.66666667 20.5       ]
a // b= [ 2  5 10 20]
a % b= [4 3 2 1]
a ** b= [537824 279841  32768   1681]


# Broadcasting

In general, when NumPy expects arrays of the same shape but finds that this is not the case, it applies the so-called broadcasting rules:

# First rule

f the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.

In [60]:
h = np.arange(5).reshape(1, 1, 5)
h

array([[[0, 1, 2, 3, 4]]])

Now let's try to add a 1D array of shape (5,) to this 3D array of shape (1,1,5). Applying the first rule of broadcasting!

In [61]:
h + [10,20,30,40,50]

array([[[10, 21, 32, 43, 54]]])

# Second rule

Arrays with a 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is repeated along that dimension.

In [62]:
k = np.arange(6).reshape(2,3)
k

array([[0, 1, 2],
       [3, 4, 5]])

Let's try to add a 2D array of shape (2,1) to this 2D ndarray of shape (2, 3). NumPy will apply the second rule of broadcasting:

In [63]:
 k + [[100], [200]]

array([[100, 101, 102],
       [203, 204, 205]])

Combining rules 1 & 2, we can do this:

In [64]:
k + [100, 200, 300]

array([[100, 201, 302],
       [103, 204, 305]])

In [65]:
k + 1000

array([[1000, 1001, 1002],
       [1003, 1004, 1005]])

# Third rule

In [69]:
try:
    k + [33, 44]
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


# Upcasting

When trying to combine arrays with different dtypes, NumPy will upcast to a type capable of handling all possible values (regardless of what the actual values are).

In [70]:
k1 = np.arange(0,5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [71]:
k2 = k1 + np.array([5,6,7,8,9], dtype=np.int8)
print(k2.dtype, k2)

int16 [ 5  7  9 11 13]


In [72]:
k3 = k1 + 1.5
print(k3.dtype, k3)

float64 [1.5 2.5 3.5 4.5 5.5]


# Conditional operators

In [73]:
# The conditional operators also apply elementwise
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [74]:
m < 25

array([ True,  True, False, False])

In [75]:
m[m<25]

array([20, -5])

# Mathematical and statistical function

many mathematical and statistical function are avaliable for ndarray

# ndarray methods

In [77]:
a =np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean=", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean= 6.766666666666667


In [78]:
# Here are a few more useful ndarray methods:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


These functions accept an optional argument axis which lets you ask for the operation to be performed on elements along the given axis. For example:

In [80]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [81]:
c.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [82]:
c.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [83]:
c.sum(axis=(0,2))

array([ 60,  92, 124])

# Universal Function

NumPy also provides fast elementwise functions called universal functions, or ufunc. They are vectorized wrappers of simple functions. For example square returns a new ndarray which is a copy of the original ndarray except that each element is squared:

In [85]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

Here are a few more useful unary ufuncs:

In [86]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sin, np.ceil, np.modf, np.isnan, np.cos):
            print("\n", func.__name__)
            print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sin
[[-0.59847214  0.04158066  0.6569866 ]
 [-0.54402111 -0.99999021 -0.53657292]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


/var/folders/r5/55rq7bkx1tg5zzbzq9whlzfh0000gn/T/ipykernel_2896/2645633744.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(func(a))
/var/folders/r5/55rq7bkx1tg5zzbzq9whlzfh0000gn/T/ipykernel_2896/2645633744.py:5: RuntimeWarning: invalid value encountered in log
  print(func(a))


# Binary ufuncs

There are also many binary ufuncs, that apply elementwise on two ndarrays. Broadcasting rules are applied if the arrays do not have the same shape:

In [87]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)

array([ 3,  6,  2, 11])

In [88]:
np.greater(a, b)

array([False, False,  True, False])

In [90]:
np.maximum(a, b)

array([2, 8, 3, 7])

In [91]:
np.copysign(a, b)

array([ 1.,  2., -3.,  4.])

# Array indexing
# One-dimensional arrays

One-dimensional NumPy arrays can be accessed more or less like regular python arrays:

In [93]:
a = np.array([1,5,3,19,13,7,3])
a[3]

19

In [94]:
a[2:5]

array([ 3, 19, 13])

In [95]:
a[:2]

array([1, 5])

In [97]:
a[2::2]

array([ 3, 13,  3])

In [98]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [99]:
a[3] = 999

In [100]:
a

array([  1,   5,   3, 999,  13,   7,   3])

In [101]:
a[2:5] = [997, 998, 999]

In [102]:
a

array([  1,   5, 997, 998, 999,   7,   3])

# Differences with regular python arrays

Contrary to regular python arrays, if you assign a single value to an ndarray slice, it is copied across the whole slice, thanks to broadcasting rules discussed above.

In [103]:
a[2:5] = -1
a

array([ 1,  5, -1, -1, -1,  7,  3])

In [105]:
try:
    a[2:5] = [1,2,3,4,5,6]
except ValueError as e:
    print(e)

could not broadcast input array from shape (6,) into shape (3,)


In [107]:
# You cannot delete elements either:
try :
    del a[2:5]
except ValueError as e:
        print(e)

cannot delete array elements


In [108]:
a_slice = a[2:6]
a_slice[1] = 1000
a

array([   1,    5,   -1, 1000,   -1,    7,    3])

In [109]:
a[3] = 2000
a_slice

array([  -1, 2000,   -1,    7])

In [110]:
# If you want a copy of the data, you need to use the copy method:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a

array([   1,    5,   -1, 2000,   -1,    7,    3])

In [111]:
a[3] = 4000
another_slice

array([  -1, 3000,   -1,    7])

# Multi-dimensional arrays

Multi-dimensional arrays can be accessed in a similar way by providing an index or slice for each axis, separated by commas:

In [112]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [113]:
b[1, 2] # row 1, col 2

14

In [114]:
b[1, :] # row 1, all columns

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [116]:
b [:, 1] # all rows, column 1

array([ 1, 13, 25, 37])

In [118]:
b[1:2, :]
# The first expression returns row 1 as a 1D array of shape (12,), while the second returns that same row as a 2D array of shape (1, 12).

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

# Fancy indexing

You may also specify a list of indices that you are interested in. This is referred to as fancy indexing.

In [119]:
b[(0,2), 2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

In [122]:
b[:,(-1, 2, -1)] # all rows, columns -1 (last), 2 and -1 (again, and in this order)

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

If you provide multiple index arrays, you get a 1D ndarray containing the values of the elements at the specified coordinates.

In [123]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)] # returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9] (again)

array([41, 33, 37, 33])

# Higher dimensions

Everything works just as well with higher dimensional arrays, but it's useful to look at a few examples:

In [124]:
c = b.reshape(4,2,6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [125]:
c[2,1,4] # matrix 2, row 1, col 4

34

In [126]:
c[2, :, 3] # matrix 2, all rows, col 3

array([27, 33])

If you omit coordinates for some axes, then all elements in these axes are returned:

In [128]:
c[2, 1] # Return matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

array([30, 31, 32, 33, 34, 35])

# Ellipsis (...)

You may also write an ellipsis (...) to ask that all non-specified axes be entirely included.

In [129]:
c[2, ...] #  matrix 2, all rows, all columns.  This is equivalent to c[2, :, :]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [130]:
c[2, 1, ...] # matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

array([30, 31, 32, 33, 34, 35])

In [131]:
c[..., 3] # all matrices, all rows, column 3.  This is equivalent to c[:, :, 3]

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45]])

# Boolean indexing

You can also provide an ndarray of boolean values on one axis to specify the indices that you want to access.

In [132]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [133]:
rows_on = np.array([True, False, True, False])
b[rows_on, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [134]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]  # All rows, columns 1, 4, 7 and 10

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

# np.ix_

You cannot use boolean indexing this way on multiple axes, but you can work around this by using the ix_ function:

In [135]:
b[np.ix_(rows_on, cols_on)]

array([[ 1,  4,  7, 10],
       [25, 28, 31, 34]])

In [136]:
np.ix_(rows_on, cols_on)

(array([[0],
        [2]]),
 array([[ 1,  4,  7, 10]]))

If you use a boolean array that has the same shape as the ndarray, then you get in return a 1D array containing all the values that have True at their coordinate. This is generally used along with conditional operators:

In [137]:
b[b % 3 == 1]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])

# Iterating

Iterating over ndarrays is very similar to iterating over regular python arrays. Note that iterating over multidimensional arrays is done with respect to the first axis.

In [138]:
c = np.arange(24). reshape(2,3,4) # A 3D array (composed of two 3x4 matrices)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [139]:
for m in c:
    print("Item:")
    print(m)

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [140]:
for i in range(len(c)):
    print("Item:")
    print(c[i])

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


If you want to iterate on all elements in the ndarray, simply iterate over the flat attribute:

In [141]:
for i in c.flat:
    print("Item:", i)

Item: 0
Item: 1
Item: 2
Item: 3
Item: 4
Item: 5
Item: 6
Item: 7
Item: 8
Item: 9
Item: 10
Item: 11
Item: 12
Item: 13
Item: 14
Item: 15
Item: 16
Item: 17
Item: 18
Item: 19
Item: 20
Item: 21
Item: 22
Item: 23


# Stacking arrays

It is often useful to stack together different arrays. NumPy offers several functions to do just that. Let's start by creating a few arrays.

In [142]:
q1 = np.full((3,4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [143]:
q2 = np.full((4,4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [144]:
q3 = np.full((3,4), 3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

# vstack

Now let's stack them vertically using vstack:

In [145]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [146]:
q4.shape

(10, 4)

This was possible because q1, q2 and q3 all have the same shape (except for the vertical axis, but that's ok since we are stacking on that axis).

# hstack

We can also stack arrays horizontally using hstack:

In [149]:
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [151]:
q5.shape

(3, 8)

This is possible because q1 and q3 both have 3 rows. But since q2 has 4 rows, it cannot be stacked horizontally with q1 and q3:

In [152]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


# concatenate

The concatenate function stacks arrays along any given existing axis.

In [153]:
q7 = np.concatenate((q1, q2, q3), axis=0) # Equivalent to vstack
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [154]:
q7.shape

(10, 4)

As you might guess, hstack is equivalent to calling concatenate with axis=1.

In [155]:
q8 = np.stack((q1, q3))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [156]:
q8.shape

(2, 3, 4)

# Splitting arrays

Splitting is the opposite of stacking. For example, let's use the vsplit function to split a matrix vertically.

First let's create a 6x4 matrix:

In [157]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [158]:
r1, r2, r3 = np.vsplit(r, 3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [159]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [160]:
r3

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

There is also a split function which splits an array along any given axis. Calling vsplit is equivalent to calling split with axis=0. There is also an hsplit function, equivalent to calling split with axis=1:

In [161]:
r4, r5 = np.hsplit(r, 2)
r4

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [162]:
r5

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

# Transposing arrays

The transpose method creates a new view on an ndarray's data, with axes permuted in the given order.

For example, let's create a 3D array:

In [163]:
t = np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

Now let's create an ndarray such that the axes 0, 1, 2 (depth, height, width) are re-ordered to 1, 2, 0 (depth→width, height→depth, width→height):

In [164]:
t1 = t.transpose((1,2,0))
t1

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [165]:
t1.shape

(2, 3, 4)

In [167]:
t2 = t.transpose()
t2

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

In [168]:
t2.shape

(3, 2, 4)

NumPy provides a convenience function swapaxes to swap two axes. For example, let's create a new view of t with depth and height swapped:

In [169]:
t3 = t.swapaxes(0,1) # equivalent to t.transpose((1, 0, 2))
t3

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])

In [170]:
t3.shape

(2, 4, 3)

# Linear algebra

NumPy 2D arrays can be used to represent matrices efficiently in python. We will just quickly go through some of the main matrix operations available. For more details about Linear Algebra, vectors and matrics, go through the Linear Algebra tutorial.

# Matrix transpose

The T attribute is equivalent to calling transpose() when the rank is ≥2:

In [171]:
m1 = np.arange(10).reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [172]:
m1 = np.arange(10). reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [173]:
m1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

The T attribute has no effect on rank 0 (empty) or rank 1 arrays:

In [174]:
m2 = np.arange(5)
m2

array([0, 1, 2, 3, 4])

In [175]:
m2.T

array([0, 1, 2, 3, 4])

We can get the desired transposition by first reshaping the 1D array to a single-row matrix (2D):

In [176]:
m2r = m2.reshape(1,5)
m2r

array([[0, 1, 2, 3, 4]])

In [177]:
m2r = m2.reshape(1,5)
m2r

array([[0, 1, 2, 3, 4]])

In [178]:
m2r.T

array([[0],
       [1],
       [2],
       [3],
       [4]])

# Matrix multiplication

Let's create two matrices and execute a matrix multiplication using the dot() method.

In [180]:
n1 = np.arange(10).reshape(2, 5)
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [181]:
n2 =np.arange(15).reshape(5,3)
n2


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [182]:
n1.dot(n2)

array([[ 90, 100, 110],
       [240, 275, 310]])

Caution: as mentionned previously, n1*n2 is not a matric multiplication, it is an elementwise product (also called a Hadamard product)).

# Matrix inverse and pseudo-inverse

Many of the linear algebra functions are available in the numpy.linalg module, in particular the inv function to compute a square matrix's inverse:

In [183]:
import numpy.linalg as linalg
m3 = np.array([[1,2,3], [5,7,11], [21, 29, 31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [184]:
linalg.inv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

You can also compute the pseudoinverse using pinv:

In [185]:
linalg.pinv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

# Identity matrix

The product of a matrix by its inverse returns the identiy matrix (with small floating point errors):

In [186]:
m3.dot(linalg.inv(m3))

array([[ 1.00000000e+00, -1.66533454e-16,  2.77555756e-17],
       [-1.40859546e-15,  1.00000000e+00,  5.55111512e-17],
       [-4.65599781e-15, -2.27595720e-15,  1.00000000e+00]])

In [187]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# QR decomposition

The qr function computes the QR decomposition of a matrix:

In [188]:
q, r = linalg.qr(m3)
q

array([[-0.04627448,  0.98786672,  0.14824986],
       [-0.23137241,  0.13377362, -0.96362411],
       [-0.97176411, -0.07889213,  0.22237479]])

In [189]:
r

array([[-21.61018278, -29.89331494, -32.80860727],
       [  0.        ,   0.62427688,   1.9894538 ],
       [  0.        ,   0.        ,  -3.26149699]])

In [190]:
q.dot(r)

array([[ 1.,  2.,  3.],
       [ 5.,  7., 11.],
       [21., 29., 31.]])

# Determinant

The det function computes the matrix determinant:

In [192]:
linalg.det(m3)

43.99999999999999

# Eigenvalues and eigenvectors

The eig function computes the eigenvalues and eigenvectors of a square matrix:

In [193]:
eigenvalues, eigenvectors = linalg.eig(m3)
eigenvalues

array([42.26600592, -0.35798416, -2.90802176])

In [194]:
eigenvectors

array([[-0.08381182, -0.76283526, -0.18913107],
       [-0.3075286 ,  0.64133975, -0.6853186 ],
       [-0.94784057, -0.08225377,  0.70325518]])

In [195]:
m3.dot(eigenvectors) - eigenvalues * eigenvectors

array([[6.21724894e-15, 2.77555756e-16, 1.44328993e-15],
       [0.00000000e+00, 3.44169138e-15, 5.55111512e-15],
       [2.13162821e-14, 8.28850877e-15, 1.19904087e-14]])

# Singular Value Decomposition

The svd function takes a matrix and returns its singular value decomposition:

In [196]:
m4 = np.array([[1,0,0,0,2], [0,0,3,0,0], [0,0,0,0,0], [0,2,0,0,0]])
m4

array([[1, 0, 0, 0, 2],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0]])

In [197]:
U, S_diag, V = linalg.svd(m4)
U

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  0.]])

In [198]:
S_diag

array([3.        , 2.23606798, 2.        , 0.        ])

The svd function just returns the values in the diagonal of Σ, but we want the full Σ matrix, so let's create it:

In [199]:
S = np.zeros((4, 5))
S[np.diag_indices(4)] = S_diag
S

array([[3.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.23606798, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [200]:
V

array([[-0.        ,  0.        ,  1.        , -0.        ,  0.        ],
       [ 0.4472136 , -0.        , -0.        , -0.        ,  0.89442719],
       [ 0.        , -1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]])

In [201]:
U.dot(S).dot(V)

array([[1., 0., 0., 0., 2.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.]])

# Diagonal and trace

In [202]:
np.diag(m3)

array([ 1,  7, 31])

In [203]:
np.trace(m3)

39

# Solving a system of linear scalar equations

The solve function solves a system of linear scalar equations, such as:
    2x + 6y =6
    5x + 3y = -9

In [205]:
coeffs = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

array([-3.,  2.])

In [206]:
coeffs.dot(solution), depvars

(array([ 6., -9.]), array([ 6, -9]))

In [207]:
np.allclose(coeffs.dot(solution), depvars)

True

# Vectorization

Instead of executing operations on individual array items, one at a time, your code is much more efficient if you try to stick to array operations. This is called vectorization. This way, you can benefit from NumPy's many optimizations.

For example, let's say we want to generate a 768x1024 array based on the formula . A bad option would be to do the math in python using nested loops:

In [208]:
import math
data = np.empty((768, 1024))
for y in range(768):
    for x in range(1024):
        data[y, x] = math.sin(x*y/40.5)

Sure, this works, but it's terribly inefficient since the loops are taking place in pure python. Let's vectorize this algorithm. First, we will use NumPy's meshgrid function which generates coordinate matrices from coordinate vectors.

In [209]:
x_coords = np.arange(0, 1024)
y_coords = np.arange(0, 768)
X, Y = np.meshgrid(x_coords, y_coords)
X

array([[   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023],
       ...,
       [   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023],
       [   0,    1,    2, ..., 1021, 1022, 1023]])

In [ ]:
Y

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   1,   1,   1],
       [  2,   2,   2, ...,   2,   2,   2],
       ...,
       [765, 765, 765, ..., 765, 765, 765],
       [766, 766, 766, ..., 766, 766, 766],
       [767, 767, 767, ..., 767, 767, 767]])